OPTION_ONE = YES = OPTION_LOGR = b'1'
OPTION_TWO = NO = OPTION_NN = b'2'
OPTION_SGD = OPTION_EVALUATE = b'3'
OPTION_CHANGE_CHOOSING_METHOD = OPTION_CANCEL = b'7'
INTERRUPT = b'\x04'

TEXT_OPTION_ONE = TEXT_YES = TEXT_OPTION_LOGR = OPTION_ONE.decode('utf-8')
TEXT_OPTION_TWO = TEXT_NO = TEXT_OPTION_NN = OPTION_TWO.decode('utf-8')
TEXT_OPTION_SGD = TEXT_OPTION_EVALUATE = OPTION_SGD.decode('utf-8')
TEXT_OPTION_CHANGE_CHOOSING_METHOD = TEXT_OPTION_CANCEL = OPTION_CANCEL.decode('utf-8')

EXTENSION_LOGR = '.logr'
EXTENSION_NN = '.nn'
EXTENSION_TFIDF = '.tfidf'
EXTENSION_DATASET = '.csv'
EXTENSION_SGD = 'sgd'
EXTENSION_REPORT = 'report'

MODEL_LOGR = 'logr'
MODEL_NN = 'nn'
MODEL_SGD = 'sgd'

DIR_MODEL = 'models'
DIR_TFIDF = 'tfidfs'
DIR_REPORT = 'reports'